### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by pierroz127** [nexmo-community/voice-google-speechtotext#9]
Hi 
I've cloned the repo as is, set up everything according to the README but... it doesn't work. 
First, line 161, I've got an exception "ReferenceError: request is not defined" after I enter the number of the language in the phone call.
After that, if I comment this line, I don't have the audio stream in run-time. I just have the recording downloaded at the end. Where is it supposed to conect to the nexmo websocket voice api?

**Comment by AlwellKevin** [comment]
Hi @pierroz127, have you tried doing an npm install request? Seems like the module is missing from package.json.

**Comment by tbass134** [comment]
hi @pierroz127  looks like the request module isn't installed. In your console, install the request model using `npm install request --save`. 
Then restart your application

**Comment by sivang** [comment]
hi there, the demo is not working for me as well with the followng error (installed request):

```
TypeError: Cannot set property 'languageCode' of undefined
    at WebSocketConnection.<anonymous> (/home/ubuntu/voice-google-speechtotext/server.js:167:37)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/home/ubuntu/voice-google-speechtotext/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/ubuntu/voice-google-speechtotext/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The request object there does not exist.
